
name: swlabels_example
description: Example of working with the package SWLabels
version: 0.1.0
homepage: ilnv@mail.ru
repository: https://github.com/iLnaar/swlabels_example
issue_tracker: https://github.com/iLnaar/swlabels_example/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  spritewidget: ^0.9.24
  swlabels: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
